app = "feitu"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  H2_CONSOLE_ENABLED = "false"
  SPRING_PROFILES_ACTIVE = "prod"
  DB_PATH = "/data/feitu-v2"

[[mounts]]
  source = "feitu_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/actuator/health"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
