app = "feitu"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  H2_CONSOLE_ENABLED = "false"
  SPRING_PROFILES_ACTIVE = "prod"

[[mounts]]
  source = "feitu_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.http_checks]
    interval = "30s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/actuator/health"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
